### ISSUE TITLE
Insertion points

### ISSUE THREAD

**Issue by tbkka** [apple/swift-protobuf-plugin#1]
The protoc-gen-swift plugin should include appropriate insertion points in the generated code that can be used by other plugins.  For example, this would allow a separate plugin to insert gRPC support.

General information about insertion points:

   https://developers.google.com/protocol-buffers/docs/reference/other

Specific examples of other generators that put insertion points into their output:

C++: https://developers.google.com/protocol-buffers/docs/reference/cpp-generated#plugins
Java: https://developers.google.com/protocol-buffers/docs/reference/java-generated#plugins

**Comment by jcanizales** [comment]
@TimBurks @muxi FYI
